{
    Info<< "/*---------------------------------------------------------------------------*\\\n"
        << "|    poroMechanicalFoam is a extention to solids4Foam. For Information on    |\n"
        << "|    poroMechanicalFoam or solids4Foam, please consult                       |\n"
        << "|    the projects communication channels.                                    |\n"
        << "\\*---------------------------------------------------------------------------*/"
        << nl << endl;
}
